site_name: OpenGRC Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Foundations: foundations.md
  - Updating: updating.md
  - Configuration: configuration.md
  - Single-Sign-On: 
    - Microsoft Azure: sso/azure.md
    - Okta: sso/okta.md
    - Google Workspaces: sso/google.md
    - Auth0: sso/auth0.md
  - API: 
    - REST API: api.md
