site_name: OpenGRC Documentation
theme: readthedocs
repo_url: https://github.com/LeeMangold/opengrc-docs
edit_uri: edit/main/docs/
nav:
  - Getting Started:
    - Getting Started: index.md    
    - Installation: installation.md
    - Updating: updating.md
  - GRC Foundations:
    - Important Terms: foundations/key-terms.md
    - Audits: foundations/audits.md
    - Workflows: foundations/workflows.md
  - Features:
    - Trust Center: features/trustcenter.md
    - Policies: features/policies.md
    - Vendor Risk Management (TPRM): features/vendor-management.md
    - Risk Management: features/risk-management.md
    - Asset Management: features/assets.md
    - Applications: features/applications.md    
  - Configuration:
    - AWS Storage: aws-storage.md  
  - Single-Sign-On: 
    - Microsoft Azure: sso/azure.md
    - Okta: sso/okta.md
    - Google Workspaces: sso/google.md
    - Auth0: sso/auth0.md
  - API:
    - REST API: api.md
  - Contributing: contributing.md
