site_name: OpenGRC Documentation
site_url: https://docs.opengrc.com
site_description: Comprehensive documentation for OpenGRC, the open-source Governance, Risk, and Compliance
site_author: OpenGRC, LLC
theme:
  name: material
  logo: img/logo-256.png
  favicon: img/favicon-32x32.png
  palette:
    primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - privacy
  - search
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
repo_url: https://github.com/LeeMangold/OpenGRC
edit_uri: edit/main/docs/
nav:
  - Getting Started:
    - Getting Started: index.md    
    - Installation: installation.md
    - Updating: updating.md
  - GRC Foundations:
    - Important Terms: foundations/key-terms.md
    - Audits: foundations/audits.md
    - Workflows: foundations/workflows.md
  - Features:
    - Trust Center: features/trustcenter.md
    - Policies: features/policies.md
    - Vendor Risk Management (TPRM): features/vendor-management.md
    - Risk Management: features/risk-management.md
    - Asset Management: features/assets.md
    - Applications: features/applications.md    
  - Configuration:
    - Settings:
      - General: settings/general.md
      - AI: settings/ai.md
      - Authentication: settings/authentication.md
      - Mail: settings/mail.md
      - Mail Templates: settings/mail-templates.md
      - Reports: settings/reports.md
      - Security: settings/security.md
      - Storage: settings/storage.md
      - AWS Storage: settings/aws-storage.md
      - Trust Center: settings/trust-center.md
      - Vendor Portal: settings/vendor-portal.md
    - Single-Sign-On:
      - Microsoft Azure: sso/azure.md
      - Okta: sso/okta.md
      - Google Workspaces: sso/google.md
      - Auth0: sso/auth0.md
  - API:
    - REST API: api.md
  - Contributing: contributing.md
